import type { Listing } from "@/types/listings";

export async function scrapeOlx(city: string): Promise<Listing[]> {
  return [
    {
      title: "Lead apartment in Krakow",
      price: 4435,
      link: "https://www.olx.pl/example1",
      city: "Krakow",
      rooms: 3,
    },
    {
      title: "Prevent apartment in Gdansk",
      price: 5443,
      link: "https://www.olx.pl/example2",
      city: "Gdansk",
      rooms: 4,
    },
    {
      title: "Avoid apartment in Poznan",
      price: 4346,
      link: "https://www.olx.pl/example3",
      city: "Poznan",
      rooms: 1,
    },
    {
      title: "Something apartment in Krakow",
      price: 4307,
      link: "https://www.olx.pl/example4",
      city: "Krakow",
      rooms: 3,
    },
    {
      title: "Store apartment in Poznan",
      price: 2001,
      link: "https://www.olx.pl/example5",
      city: "Poznan",
      rooms: 2,
    },
    {
      title: "Improve apartment in Krakow",
      price: 2007,
      link: "https://www.olx.pl/example6",
      city: "Krakow",
      rooms: 5,
    },
    {
      title: "Share apartment in Warsaw",
      price: 3670,
      link: "https://www.olx.pl/example7",
      city: "Warsaw",
      rooms: 4,
    },
    {
      title: "Reason apartment in Poznan",
      price: 5206,
      link: "https://www.olx.pl/example8",
      city: "Poznan",
      rooms: 2,
    },
    {
      title: "Animal apartment in Warsaw",
      price: 5595,
      link: "https://www.olx.pl/example9",
      city: "Warsaw",
      rooms: 3,
    },
    {
      title: "Clear apartment in Krakow",
      price: 2358,
      link: "https://www.olx.pl/example10",
      city: "Krakow",
      rooms: 1,
    },
    {
      title: "Son apartment in Krakow",
      price: 4907,
      link: "https://www.olx.pl/example11",
      city: "Krakow",
      rooms: 2,
    },
    {
      title: "Future apartment in Warsaw",
      price: 5064,
      link: "https://www.olx.pl/example12",
      city: "Warsaw",
      rooms: 3,
    },
    {
      title: "Operation apartment in Wroclaw",
      price: 2014,
      link: "https://www.olx.pl/example13",
      city: "Wroclaw",
      rooms: 3,
    },
    {
      title: "Hot apartment in Poznan",
      price: 3735,
      link: "https://www.olx.pl/example14",
      city: "Poznan",
      rooms: 2,
    },
    {
      title: "Ok apartment in Warsaw",
      price: 1832,
      link: "https://www.olx.pl/example15",
      city: "Warsaw",
      rooms: 4,
    },
    {
      title: "Suggest apartment in Krakow",
      price: 2373,
      link: "https://www.olx.pl/example16",
      city: "Krakow",
      rooms: 1,
    },
    {
      title: "Reflect apartment in Krakow",
      price: 4654,
      link: "https://www.olx.pl/example17",
      city: "Krakow",
      rooms: 3,
    },
    {
      title: "Form apartment in Gdansk",
      price: 2386,
      link: "https://www.olx.pl/example18",
      city: "Gdansk",
      rooms: 1,
    },
    {
      title: "Night apartment in Warsaw",
      price: 3871,
      link: "https://www.olx.pl/example19",
      city: "Warsaw",
      rooms: 2,
    },
    {
      title: "Explain apartment in Gdansk",
      price: 5766,
      link: "https://www.olx.pl/example20",
      city: "Gdansk",
      rooms: 4,
    },
    {
      title: "Hear apartment in Gdansk",
      price: 2227,
      link: "https://www.olx.pl/example21",
      city: "Gdansk",
      rooms: 4,
    },
    {
      title: "Five apartment in Poznan",
      price: 2375,
      link: "https://www.olx.pl/example22",
      city: "Poznan",
      rooms: 4,
    },
    {
      title: "Think apartment in Warsaw",
      price: 4917,
      link: "https://www.olx.pl/example23",
      city: "Warsaw",
      rooms: 4,
    },
    {
      title: "Ability apartment in Warsaw",
      price: 2659,
      link: "https://www.olx.pl/example24",
      city: "Warsaw",
      rooms: 4,
    },
    {
      title: "Story apartment in Krakow",
      price: 2547,
      link: "https://www.olx.pl/example25",
      city: "Krakow",
      rooms: 2,
    },
    {
      title: "Hundred apartment in Wroclaw",
      price: 5684,
      link: "https://www.olx.pl/example26",
      city: "Wroclaw",
      rooms: 4,
    },
    {
      title: "American apartment in Poznan",
      price: 3531,
      link: "https://www.olx.pl/example27",
      city: "Poznan",
      rooms: 5,
    },
    {
      title: "Case apartment in Gdansk",
      price: 2443,
      link: "https://www.olx.pl/example28",
      city: "Gdansk",
      rooms: 2,
    },
    {
      title: "Whose apartment in Wroclaw",
      price: 4279,
      link: "https://www.olx.pl/example29",
      city: "Wroclaw",
      rooms: 3,
    },
    {
      title: "Social apartment in Krakow",
      price: 5114,
      link: "https://www.olx.pl/example30",
      city: "Krakow",
      rooms: 1,
    },
  ];
}
